services:
  web:
    build: .
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=kidsmath

  db:
    image: mysql:8.0
    platform: linux/amd64 # This forces the amd64 image, which should work on both Intel and ARM Macs
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: kidsmath
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./setup_database.sql:/docker-entrypoint-initdb.d/setup_database.sql
    command: --default-authentication-plugin=mysql_native_password # This ensures compatibility with older clients

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
